### ISSUE TITLE
Activity Details Page

### ISSUE THREAD

**Issue by MoonTahoe** [MoonHighway/clam-ui#31]
Create the [Activity Details Page](https://clam.moonhighway.com/activity/AAA).

* [ ] Query Activity Details
* [ ] Display Activity Details Component #32
* [ ] Display Activity Type Panel, #34, #35, #36, #37  
* [ ] Display a list of counselor Thumbs #22 
* [ ] Display the participants component
* [ ] All Errors are handled and displayed
* [ ] Creative looks good
* [ ] Loading Animations as necessary
* [ ] Disabled Buttons based on state #19 
* [ ] Page looks good in all screen sizes
* [ ] Page is accessible
