### ISSUE TITLE
Authorization Page

### ISSUE THREAD

**Issue by MoonTahoe** [MoonHighway/clam-ui#7]
Create the [Authorization Page](http://clam.moonhighway.com). This page handles creating new campers, camper login, and logging in with Github.

* [ ] Campers can switch between login and register forms
* [ ] Campers can register #12 
* [ ] Campers can login #13 
* [ ] Campers can update their account #17 
* [ ] Campers can login with github #11 
* [ ] Form data is saved and populated from link-state #16, #15 
* [ ] Current camper is identified
* [ ] Current camper can update name and email
* [ ] All Errors are handled and displayed
* [ ] Creative looks good
* [ ] Loading Animations as necessary
* [ ] Disabled Buttons based on state #19 
* [ ] Page looks good in all screen sizes
* [ ] Page is accessible
