### ISSUE TITLE
Activities Page

### ISSUE THREAD

**Issue by MoonTahoe** [MoonHighway/clam-ui#8]
Create the [Activities Page](http://clam.moonhighway.com/activities). This page handles listing activities, paging activities, searching for activities, and applying filters to the activity list.

* [ ] Campers can list all activities
* [ ] Campers can scroll to list more activities
  * [ ] Infinite Scroll implements windowing
* [ ] Campers can filter activities by type, #20, #21
* [ ] Campers can search for activities, #20 
* [ ] Search and Filter details supplied by link state, #18 
* [ ] Campers can add Activities from the form
* [ ] Scheduled activities do not display the add button
* [ ] All Errors are handled and displayed
* [ ] Creative looks good
* [ ] Loading Animations as necessary
* [ ] Page looks good in all screen sizes
* [ ] Page is accessible
